---
abstract: 'Utilities for TV program genre of ARIB'
author:
  - 'moznion <moznion@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TV-ARIB-ProgramGenre
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  TV::ARIB::ProgramGenre:
    file: lib/TV/ARIB/ProgramGenre.pm
    version: 0.01
  TV::ARIB::ProgramGenre::ChildGenre:
    file: lib/TV/ARIB/ProgramGenre/ChildGenre.pm
  TV::ARIB::ProgramGenre::ChildGenre::Anime:
    file: lib/TV/ARIB/ProgramGenre/ChildGenre/Anime.pm
  TV::ARIB::ProgramGenre::ChildGenre::Documentary:
    file: lib/TV/ARIB/ProgramGenre/ChildGenre/Documentary.pm
  TV::ARIB::ProgramGenre::ChildGenre::Drama:
    file: lib/TV/ARIB/ProgramGenre/ChildGenre/Drama.pm
  TV::ARIB::ProgramGenre::ChildGenre::Expansion:
    file: lib/TV/ARIB/ProgramGenre/ChildGenre/Expansion.pm
  TV::ARIB::ProgramGenre::ChildGenre::Hobby:
    file: lib/TV/ARIB/ProgramGenre/ChildGenre/Hobby.pm
  TV::ARIB::ProgramGenre::ChildGenre::Info:
    file: lib/TV/ARIB/ProgramGenre/ChildGenre/Info.pm
  TV::ARIB::ProgramGenre::ChildGenre::Movie:
    file: lib/TV/ARIB/ProgramGenre/ChildGenre/Movie.pm
  TV::ARIB::ProgramGenre::ChildGenre::Music:
    file: lib/TV/ARIB/ProgramGenre/ChildGenre/Music.pm
  TV::ARIB::ProgramGenre::ChildGenre::News:
    file: lib/TV/ARIB/ProgramGenre/ChildGenre/News.pm
  TV::ARIB::ProgramGenre::ChildGenre::Other:
    file: lib/TV/ARIB/ProgramGenre/ChildGenre/Other.pm
  TV::ARIB::ProgramGenre::ChildGenre::Reserve:
    file: lib/TV/ARIB/ProgramGenre/ChildGenre/Reserve.pm
  TV::ARIB::ProgramGenre::ChildGenre::Sport:
    file: lib/TV/ARIB/ProgramGenre/ChildGenre/Sport.pm
  TV::ARIB::ProgramGenre::ChildGenre::Theater:
    file: lib/TV/ARIB/ProgramGenre/ChildGenre/Theater.pm
  TV::ARIB::ProgramGenre::ChildGenre::Variety:
    file: lib/TV/ARIB/ProgramGenre/ChildGenre/Variety.pm
  TV::ARIB::ProgramGenre::ChildGenre::Welfare:
    file: lib/TV/ARIB/ProgramGenre/ChildGenre/Welfare.pm
requires:
  Encode: 0
  parent: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/moznion/TV-ARIB-ProgramGenre/issues
  homepage: https://github.com/moznion/TV-ARIB-ProgramGenre
  repository: git://github.com/moznion/TV-ARIB-ProgramGenre.git
version: 0.01
